from doc.tests.HooshyarTest_ActorsSearch import *
from doc.tests.HooshyarTest_AdvancedGraph import *
from doc.tests.HooshyarTest_ClusteringResult import *
from doc.tests.HooshyarTest_DocumentIndicesExist import *
from doc.tests.HooshyarTest_KnowledgeGraph import *
from doc.tests.HooshyarTest_LDATopicExtraction import *
from doc.tests.HooshyarTest_LoginCheck import *
from doc.tests.HooshyarTest_ProfileDataCollection import *
from doc.tests.HooshyarTest_SearchActors import *
from doc.tests.HooshyarTest_SearchDetail import *
from doc.tests.HooshyarTest_SearchFilterParameters import *
from doc.tests.HooshyarTest_SubjectKeywordGraph import *